# Tensorflow

In [25]:
import numpy as np
import tensorflow as tf 
a=tf.constant(15)
b=tf.constant(20)
# Perform the addition operation
result = a + b

# Print the result
print(result.numpy())

35


In [26]:
x=np.random.rand(100).astype(np.float32)
print(x)

[1.9546014e-01 9.5577580e-01 6.5200728e-01 3.7957075e-01 5.7422513e-01
 2.0400448e-01 5.4775983e-01 2.2835977e-02 9.6715295e-01 9.8777163e-01
 3.9256993e-01 8.0312595e-02 6.3172144e-01 1.3342531e-01 9.5956993e-01
 2.7238846e-01 6.7656666e-01 3.4080103e-01 3.0755994e-01 8.3686310e-01
 6.4370088e-02 4.5199347e-01 3.4000176e-01 4.0920150e-01 6.1961305e-01
 1.5439056e-01 3.2335413e-01 1.4191122e-01 5.6571901e-01 6.8394929e-01
 2.0959134e-01 2.6370376e-01 9.5831811e-02 8.4809530e-01 7.0461506e-01
 4.1436139e-01 7.0122170e-01 4.6184874e-01 4.9500602e-01 8.3332342e-01
 9.2895168e-01 4.8289201e-01 4.8630437e-01 7.7866435e-01 5.0782162e-01
 9.2891043e-01 3.6284396e-01 8.6597478e-01 5.1566559e-01 4.9576238e-01
 7.4076178e-03 1.9294979e-02 5.8725297e-01 7.3200947e-01 4.0360160e-02
 3.9560862e-02 8.4534401e-01 5.8156985e-01 3.8672233e-01 3.2202777e-01
 7.5574404e-01 9.2348546e-01 9.1138840e-01 1.1845086e-01 7.4343538e-01
 6.9522321e-01 4.6679464e-01 5.8545828e-01 6.8372011e-01 6.3291210e-01
 3.124

In [27]:
y=x*0.2+0.2
W=tf.Variable(tf.random.normal([1]))
b=tf.Variable(tf.zeros([1]))

In [28]:
def mse_loss():
  ypred=W* x+b
  loss=tf.reduce_mean(tf.square(ypred-y))
  return loss

In [29]:
optimizer=tf.keras.optimizers.Adam()
for step in range(5000):
  optimizer.minimize(mse_loss, var_list=[W,b])
  if step % 500 == 0:
    loss = mse_loss()
    print(step,loss.numpy(),W.numpy(),b.numpy())

0 0.1665428 [1.1527128] [-0.00099999]
500 0.035393305 [0.843195] [-0.15790775]
1000 0.016464932 [0.6381128] [-0.04530998]
1500 0.0055411975 [0.45426044] [0.05788603]
2000 0.0012748685 [0.3219783] [0.13187535]
2500 0.00018107578 [0.24597292] [0.17433026]
3000 1.3828804e-05 [0.21270482] [0.19290638]
3500 4.7459062e-07 [0.20235363] [0.1986859]
4000 5.7741203e-09 [0.20025961] [0.19985504]
4500 1.8124127e-11 [0.20001456] [0.1999919]


In [34]:
optimizer = tf.keras.optimizers.Adam(learning_rate=0.01)
for step in range(5000):
    with tf.GradientTape() as tape:
        

        gradients = tape.gradient(loss, [W, b])
        optimizer.apply_gradients(zip(gradients, [W, b]))

    if step % 500 == 0:
        print(step, "Loss:", loss.numpy(), "W:", W.numpy(), "b:", b.numpy())

ValueError: No gradients provided for any variable: (['Variable:0', 'Variable:0'],). Provided `grads_and_vars` is ((None, <tf.Variable 'Variable:0' shape=(1,) dtype=float32, numpy=array([0.20000102], dtype=float32)>), (None, <tf.Variable 'Variable:0' shape=(1,) dtype=float32, numpy=array([0.19999942], dtype=float32)>)).

# Keras

In [6]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
import pandas as pd

In [8]:
dataset =  pd.read_csv('diabetes.csv', delimiter=',')
dataset

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0              6      148             72             35        0  33.6   
1              1       85             66             29        0  26.6   
2              8      183             64              0        0  23.3   
3              1       89             66             23       94  28.1   
4              0      137             40             35      168  43.1   
..           ...      ...            ...            ...      ...   ...   
763           10      101             76             48      180  32.9   
764            2      122             70             27        0  36.8   
765            5      121             72             23      112  26.2   
766            1      126             60              0        0  30.1   
767            1       93             70             31        0  30.4   

     DiabetesPedigreeFunction  Age  Outcome  
0                       0.627   50        1  
1                       0.351   31        0  
2                       0.672   32        1  
3                       0.167   21        0  
4                       2.288   33        1  
..                        ...  ...      ...  
763                     0.171   63        0  
764                     0.340   27        0  
765                     0.245   30        0  
766                     0.349   47        1  
767                     0.315   23        0  

[768 rows x 9 columns]

In [9]:
x = dataset.iloc[:,0:8]
print(x.shape)
y = dataset.iloc[:,8]
print(y)

(768, 8)
0      1
1      0
2      1
3      0
4      1
      ..
763    0
764    0
765    0
766    1
767    0
Name: Outcome, Length: 768, dtype: int64


In [10]:
model = Sequential()

In [11]:
model.add(Dense(12,input_shape=(8,),activation='relu'))

In [12]:
model.add(Dense(8, activation='relu'))

In [13]:
model.add(Dense(1,activation='sigmoid'))

In [14]:
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

In [15]:
model.fit(x,y, epochs=150, batch_size=10)

Epoch 1/150
77/77 [==============================] - 1s 1ms/step - loss: 2.9022 - accuracy: 0.5065
Epoch 2/150
77/77 [==============================] - 0s 985us/step - loss: 1.6157 - accuracy: 0.5443
Epoch 3/150
77/77 [==============================] - 0s 983us/step - loss: 1.2657 - accuracy: 0.5703
Epoch 4/150
77/77 [==============================] - 0s 967us/step - loss: 1.0704 - accuracy: 0.6094
Epoch 5/150
77/77 [==============================] - 0s 993us/step - loss: 0.9463 - accuracy: 0.6094
Epoch 6/150
77/77 [==============================] - 0s 1ms/step - loss: 0.9445 - accuracy: 0.6224
Epoch 7/150
77/77 [==============================] - 0s 988us/step - loss: 0.8175 - accuracy: 0.6615
Epoch 8/150
77/77 [==============================] - 0s 1ms/step - loss: 0.7938 - accuracy: 0.6719
Epoch 9/150
77/77 [==============================] - 0s 983us/step - loss: 0.7775 - accuracy: 0.6628
Epoch 10/150
77/77 [==============================] - 0s 973us/step - loss: 0.7319 - accuracy: 0.

In [16]:
model.evaluate(x,y)

24/24 [==============================] - 0s 1ms/step - loss: 0.5341 - accuracy: 0.7487


[0.5340813994407654, 0.7486979365348816]

# PyTorch

In [20]:
!pip install https://download.pytorch.org/whl/cpu/torch-1.0.1-cp36-cp36m-win_amd64.whl
!pip install torchvision

ERROR: torch-1.0.1-cp36-cp36m-win_amd64.whl is not a supported wheel on this platform.


  Obtaining dependency information for torchvision from https://files.pythonhosted.org/packages/20/ac/ab6f42af83349e679b03c9bb18354740c6b58b17dba329fb408730230584/torchvision-0.16.0-cp311-cp311-win_amd64.whl.metadata
  Obtaining dependency information for torch==2.1.0 from https://files.pythonhosted.org/packages/74/07/edce54779f5c3fe8ab8390eafad3d7c8190fce68f922a254ea77f4a94a99/torch-2.1.0-cp311-cp311-win_amd64.whl.metadata
   ---------------------------------------- 0.0/1.3 MB ? eta -:--:--
   - -------------------------------------- 0.0/1.3 MB 1.9 MB/s eta 0:00:01
   - -------------------------------------- 0.0/1.3 MB 1.9 MB/s eta 0:00:01
   - -------------------------------------- 0.0/1.3 MB 1.9 MB/s eta 0:00:01
   - -------------------------------------- 0.0/1.3 MB 1.9 MB/s eta 0:00:01
   - -------------------------------------- 0.1/1.3 MB 272.3 kB/s eta 0:00:05
   -- ------------------------------------- 0.1/1.3 MB 327.7 kB/s eta 0:00:04
   --- ------------------------------------

In [1]:
import torch
import numpy as np

In [2]:
#using data
data = [ 
 [1,2], 
 [3,4] 
] 
x_data = torch.tensor(data) 
print(x_data)
print(type(x_data)) 

tensor([[1, 2],
        [3, 4]])
<class 'torch.Tensor'>


In [3]:
#using numpy array 
np_array = np.array(data) 
x_np = torch.from_numpy(np_array) 
print(x_np) 
print(type(x_np))

tensor([[1, 2],
        [3, 4]], dtype=torch.int32)
<class 'torch.Tensor'>


In [4]:
#using another tensor 
x_ones = torch.ones_like(x_data) 
print("One Tensor: \n",x_ones) 
x_rand = torch.rand_like(x_data,dtype=torch.float) 
print(x_rand) 

One Tensor: 
 tensor([[1, 1],
        [1, 1]])
tensor([[0.4211, 0.9917],
        [0.9586, 0.5019]])


In [5]:
# more ways to create tensors 
shape = (2,3) 
random_tensor = torch.rand(shape) 
print(random_tensor) 
print(type(random_tensor)) 
ones_tensor = torch.ones(shape) 
print(ones_tensor) 
print(type(ones_tensor)) 
zeros_tensor = torch.zeros(shape) 
print(zeros_tensor) 
print(type(zeros_tensor)) 
tensor = torch.rand(3,4) 
print(tensor) 
print(type(tensor))

tensor([[0.9684, 0.9921, 0.8412],
        [0.4846, 0.5810, 0.2779]])
<class 'torch.Tensor'>
tensor([[1., 1., 1.],
        [1., 1., 1.]])
<class 'torch.Tensor'>
tensor([[0., 0., 0.],
        [0., 0., 0.]])
<class 'torch.Tensor'>
tensor([[0.2268, 0.6548, 0.9550, 0.8669],
        [0.9377, 0.1092, 0.0943, 0.7366],
        [0.1950, 0.4500, 0.5727, 0.2608]])
<class 'torch.Tensor'>


In [6]:
# Indexing, Slicing 
tensor = torch.ones(4,4)
print(tensor) 
print(tensor) 
tensor1 = torch.zeros(4,4) 
print(tensor1) 
tensor2 = torch.cat([tensor,tensor1]) 
print(tensor2) 

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])
tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])
tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])
tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])


In [7]:
# Multiply Operation 
tensor.mul(tensor1) 
tensor * tensor1 
tensor.T

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [8]:
# inplace - change the original tensor 
tensor.add_(3) 
print(tensor) 

tensor([[4., 4., 4., 4.],
        [4., 4., 4., 4.],
        [4., 4., 4., 4.],
        [4., 4., 4., 4.]])


In [9]:
# from tensor to numpy 
t = torch.ones(5) 
print(t) 
n = t.numpy() 
print(n) 
print(type(n)) 

tensor([1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1.]
<class 'numpy.ndarray'>
